apiVersion: v1
kind: Service
metadata:
  name: {{ include "global-lb.fullname" . }}-headless
  labels:
    {{- include "global-lb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "global-lb.selector" . | nindent 4 }}
    app.kubernetes.io/component: haproxy
  ports:
    - name: health
      port: 8404
      targetPort: health
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "global-lb.fullname" . }}
  labels:
    {{- include "global-lb.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if ne .Values.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  selector:
    {{- include "global-lb.selector" . | nindent 4 }}
    app.kubernetes.io/component: haproxy
  ports:
    {{- range .Values.backends }}
    - name: {{ .portName }}
      port: {{ .port }}
      targetPort: {{ .portName }}
      protocol: TCP
    {{- end }}
