/* Generated from dev/global-lb/reserve.lua; do not edit.
 * UD-007/009/011 v2-r1-20261003. */
static const char global_lb_reserve_lua[] =
"-- UD-007/009/011 v2-r1-20261003. Redis/Valkey standalone RESP2 protocol.\n"
"-- KEYS: owners, liveness, counts, active requests. All keys are explicit.\n"
"-- ARGV: op, hex(instance), UUID, revision, request-id, high-water, timeout-ms,\n"
"--       tie-seed, max-instances, max-count-fields, max-requests, service,\n"
"--       candidate-count, candidates..., snapshot-count, request/endpoint...\n"
"-- request IDs/revisions use exact uint64 decimal comparison, never doubles.\n"
"local function reply(code, endpoint, count) return {code, endpoint or '', count or 0} end\n"
"local function uint(s, zero, max)\n"
"    return s and string.match(s, '^%d+$') and (#s == 1 or string.sub(s, 1, 1) ~= '0')\n"
"        and (zero or s ~= '0') and (#s < #max or (#s == #max and s <= max))\n"
"end\n"
"local function cmp(a, b)\n"
"    if #a ~= #b then return #a < #b and -1 or 1 end\n"
"    if a == b then return 0 end\n"
"    return a < b and -1 or 1\n"
"end\n"
"local function uuid(s)\n"
"    return s and #s == 36 and string.match(s,\n"
"        '^%x%x%x%x%x%x%x%x%-%x%x%x%x%-4%x%x%x%-[89ab]%x%x%x%-%x%x%x%x%x%x%x%x%x%x%x%x$')\n"
"        and s == string.lower(s)\n"
"end\n"
"local max64, maxint, maxexact = '18446744073709551615', '2147483647', '9007199254740991'\n"
"if #KEYS ~= 4 or #ARGV < 14 then return reply(-2) end\n"
"for i = 1, 4 do\n"
"    if #KEYS[i] == 0 then return reply(-2) end\n"
"    for j = 1, i-1 do if KEYS[i] == KEYS[j] then return reply(-2) end end\n"
"    local t = redis.call('TYPE', KEYS[i]).ok\n"
"    if t ~= 'none' and t ~= 'hash' then return reply(-3) end\n"
"end\n"
"local op, iid, gen, rev, rid, water = unpack(ARGV, 1, 6)\n"
"local valid_ops = {start=true, restore=true, reserve=true, release=true,\n"
"                   cancel=true, heartbeat=true, stop=true}\n"
"if not valid_ops[op] or #iid == 0 or #iid % 2 ~= 0 or not string.match(iid, '^[0-9a-f]+$')\n"
"    or not uuid(gen) or not uint(rev, false, max64) or not uint(rid, true, max64)\n"
"    or not uint(water, true, max64) then return reply(-2) end\n"
"for i = 7, 11 do if not uint(ARGV[i], false, maxint) then return reply(-2) end end\n"
"local timeout, seed, maxinst, maxfields, maxreq = unpack(ARGV, 7, 11)\n"
"timeout, seed = tonumber(timeout), tonumber(seed)\n"
"maxinst, maxfields, maxreq = tonumber(maxinst), tonumber(maxfields), tonumber(maxreq)\n"
"local service = ARGV[12]\n"
"if not uint(ARGV[13], true, maxint) then return reply(-2) end\n"
"local nc = tonumber(ARGV[13])\n"
"if nc > maxfields or 14 + nc > #ARGV then return reply(-5) end\n"
"local candidates, seen = {}, {}\n"
"for i = 1, nc do\n"
"    local e = ARGV[13+i]\n"
"    if #service == 0 or string.sub(e, 1, #service+1) ~= service .. '|'\n"
"        or #e <= #service+1 or seen[e] then return reply(-2) end\n"
"    seen[e], candidates[i] = true, e\n"
"end\n"
"local pos = 14 + nc\n"
"if not uint(ARGV[pos], true, maxint) then return reply(-2) end\n"
"local ns = tonumber(ARGV[pos])\n"
"if ns > maxreq then return reply(-5) end\n"
"if #ARGV ~= pos + 2*ns then return reply(-2) end\n"
"local control = op == 'start' or op == 'restore'\n"
"local request = op == 'reserve' or op == 'release' or op == 'cancel'\n"
"if (request and rid == '0') or (not request and rid ~= '0')\n"
"    or (not control and (ns ~= 0 or water ~= '0'))\n"
"    or (op == 'reserve' and nc == 0) or (op ~= 'reserve' and nc ~= 0) then return reply(-2) end\n"
"local snapshot, newcounts = {}, {}\n"
"for i = 1, ns do\n"
"    local id, e = ARGV[pos+2*i-1], ARGV[pos+2*i]\n"
"    if not uint(id, false, max64) or cmp(id, water) > 0 or snapshot[id]\n"
"        or not string.match(e, '^.+|.+$') then return reply(-2) end\n"
"    snapshot[id] = e\n"
"    newcounts[e] = (newcounts[e] or 0) + 1\n"
"end\n"
"if redis.call('HLEN', KEYS[1]) > maxinst or redis.call('HLEN', KEYS[2]) > maxinst\n"
"    or redis.call('HLEN', KEYS[3]) > maxfields or redis.call('HLEN', KEYS[4]) > maxreq then return reply(-5) end\n"
"local tm = redis.call('TIME')\n"
"local now = tonumber(tm[1])*1000 + math.floor(tonumber(tm[2])/1000)\n"
"local function metadata(id)\n"
"    local value = redis.call('HGET', KEYS[2], id)\n"
"    if not value then return nil end\n"
"    local r, hb, high, state = string.match(value, '^(%d+)|(%d+)|(%d+)|([ARD])$')\n"
"    if not uint(r, false, max64) or not uint(hb, true, maxexact)\n"
"        or not uint(high, true, max64) or tonumber(hb) > now then return nil end\n"
"    return {rev=r, hb=tonumber(hb), water=high, state=state}\n"
"end\n"
"local oldgen = redis.call('HGET', KEYS[1], iid)\n"
"local meta = metadata(iid)\n"
"if oldgen and (not uuid(oldgen) or not meta) then return reply(-3) end\n"
"if not oldgen and redis.call('HEXISTS', KEYS[2], iid) == 1\n"
"    and not (control and meta and meta.state == 'R') then return reply(-3) end\n"
"if oldgen and oldgen ~= gen and op ~= 'start' then return reply(-1) end\n"
"if not oldgen and not control then return reply(5) end\n"
"if oldgen == gen then\n"
"    if control then\n"
"        if meta.state == 'D' then return reply(-7) end\n"
"        local c = cmp(rev, meta.rev)\n"
"        if c < 0 then return reply(-4) end\n"
"        -- Confirming a repeated replacement MUST NOT erase later reservations.\n"
"        if c == 0 then\n"
"            if meta.state ~= 'A' then return reply(-7) end\n"
"            return reply(2)\n"
"        end\n"
"        if cmp(water, meta.water) < 0 then return reply(-4) end\n"
"    -- UD-011 v2-r3-20261003: exclusion depends on UUID, not an uncertain local restore\n"
"    -- revision. Drain the command first; STOP cannot delete another writer.\n"
"    elseif op ~= 'stop' and rev ~= meta.rev then return reply(-4) end\n"
"end\n"
"if not control and meta.state ~= 'A' and op ~= 'stop' then return reply(-7) end\n"
"if (op == 'reserve' or op == 'heartbeat') and now-meta.hb > timeout then return reply(-6) end\n"
"local prefix = iid .. '|'\n"
"local function own_fields(key)\n"
"    local out = {}\n"
"    for _, field in ipairs(redis.call('HKEYS', key)) do\n"
"        if string.sub(field, 1, #prefix) == prefix then out[#out+1] = field end\n"
"    end\n"
"    return out\n"
"end\n"
"local owncounts, ownreq, endpoint, total = {}, {}, nil, 0\n"
"if control or op == 'stop' then\n"
"    owncounts, ownreq = own_fields(KEYS[3]), own_fields(KEYS[4])\n"
"    local nn = 0\n"
"    for _ in pairs(newcounts) do nn = nn+1 end\n"
"    if redis.call('HLEN', KEYS[3]) - #owncounts + nn > maxfields\n"
"        or redis.call('HLEN', KEYS[4]) - #ownreq + ns > maxreq\n"
"        or (not oldgen and redis.call('HLEN', KEYS[1]) >= maxinst) then return reply(-5) end\n"
"elseif op == 'reserve' then\n"
"    local owners = redis.call('HGETALL', KEYS[1])\n"
"    local active = {}\n"
"    for i = 1, #owners, 2 do\n"
"        local id, g = owners[i], owners[i+1]\n"
"        local m = metadata(id)\n"
"        if #id == 0 or #id % 2 ~= 0 or not string.match(id, '^[0-9a-f]+$')\n"
"            or not uuid(g) or not m then return reply(-3) end\n"
"        if m.state == 'A' and now-m.hb <= timeout then active[#active+1] = id end\n"
"    end\n"
"    local function aggregate(e)\n"
"        local sum = 0\n"
"        for _, id in ipairs(active) do\n"
"            local n = redis.call('HGET', KEYS[3], id .. '|' .. e)\n"
"            if n then\n"
"                if not uint(n, true, maxint) then return nil, -3 end\n"
"                sum = sum+tonumber(n)\n"
"                if sum >= tonumber(maxexact) then return nil, -5 end\n"
"            end\n"
"        end\n"
"        return sum\n"
"    end\n"
"    endpoint = redis.call('HGET', KEYS[4], prefix .. rid)\n"
"    if endpoint then\n"
"        if string.sub(endpoint, 1, #service+1) ~= service .. '|' then return reply(-3) end\n"
"        local n = redis.call('HGET', KEYS[3], prefix .. endpoint)\n"
"        if not uint(n, false, maxint) then return reply(-3) end\n"
"        local sum, error = aggregate(endpoint)\n"
"        if not sum then return reply(error) end\n"
"        return reply(2, endpoint, sum)\n"
"    end\n"
"    if cmp(rid, meta.water) <= 0 then return reply(0) end\n"
"    if redis.call('HLEN', KEYS[4]) >= maxreq then return reply(-5) end\n"
"    local best, ties = nil, {}\n"
"    for _, e in ipairs(candidates) do\n"
"        local sum, error = aggregate(e)\n"
"        if not sum then return reply(error) end\n"
"        if not best or sum < best then best, ties = sum, {e}\n"
"        elseif sum == best then ties[#ties+1] = e end\n"
"    end\n"
"    math.randomseed(seed)\n"
"    endpoint = ties[math.random(#ties)]\n"
"    total = best+1\n"
"    local n = redis.call('HGET', KEYS[3], prefix .. endpoint)\n"
"    if n and not uint(n, true, maxint) then return reply(-3) end\n"
"    if n and tonumber(n) >= tonumber(maxint) then return reply(-5) end\n"
"    if not n and redis.call('HLEN', KEYS[3]) >= maxfields then return reply(-5) end\n"
"elseif op == 'release' or op == 'cancel' then\n"
"    endpoint = redis.call('HGET', KEYS[4], prefix .. rid)\n"
"    if endpoint then\n"
"        local n = redis.call('HGET', KEYS[3], prefix .. endpoint)\n"
"        if not uint(n, false, maxint) then return reply(-3) end\n"
"    end\n"
"end\n"
"local function setmeta(state, r, hb, high)\n"
"    redis.call('HSET', KEYS[2], iid, r .. '|' .. string.format('%.0f', hb) .. '|' .. high .. '|' .. state)\n"
"end\n"
"-- Runtime write errors do not roll back Lua. Exclude this instance until a\n"
"-- fresh revision restore succeeds; error replies are never reserve success.\n"
"local ok, result = pcall(function()\n"
"    if control or op == 'stop' then\n"
"        local r = control and rev or meta.rev\n"
"        local high = control and water or meta.water\n"
"        setmeta('R', r, now, high)\n"
"        redis.call('HSET', KEYS[1], iid, gen)\n"
"        for _, f in ipairs(owncounts) do redis.call('HDEL', KEYS[3], f) end\n"
"        for _, f in ipairs(ownreq) do redis.call('HDEL', KEYS[4], f) end\n"
"        if control then\n"
"            for id, e in pairs(snapshot) do redis.call('HSET', KEYS[4], prefix .. id, e) end\n"
"            for e, n in pairs(newcounts) do redis.call('HSET', KEYS[3], prefix .. e, n) end\n"
"        end\n"
"        setmeta(op == 'stop' and 'D' or 'A', r, now, high)\n"
"        return reply(1)\n"
"    elseif op == 'heartbeat' then\n"
"        setmeta('A', meta.rev, now, meta.water)\n"
"        return reply(1)\n"
"    else\n"
"        local high = cmp(rid, meta.water) > 0 and rid or meta.water\n"
"        setmeta('R', meta.rev, meta.hb, high)\n"
"        if op == 'reserve' then\n"
"            redis.call('HINCRBY', KEYS[3], prefix .. endpoint, 1)\n"
"            redis.call('HSET', KEYS[4], prefix .. rid, endpoint)\n"
"        elseif endpoint then\n"
"            local n = redis.call('HINCRBY', KEYS[3], prefix .. endpoint, -1)\n"
"            if n == 0 then redis.call('HDEL', KEYS[3], prefix .. endpoint) end\n"
"            redis.call('HDEL', KEYS[4], prefix .. rid)\n"
"        end\n"
"        setmeta('A', meta.rev, meta.hb, high)\n"
"        if op == 'reserve' then return reply(1, endpoint, total) end\n"
"        if not endpoint then return reply(op == 'cancel' and 4 or 5) end\n"
"        return reply(op == 'cancel' and 4 or 3, endpoint)\n"
"    end\n"
"end)\n"
"if not ok then\n"
"    -- Best effort only: allocation/ACL failures may also prevent invalidation.\n"
"    -- The caller must fallback and reconnect/restore after ANY error.\n"
"    if redis.call('HGET', KEYS[1], iid) == gen then\n"
"        redis.pcall('HSET', KEYS[2], iid, rev .. '|' .. string.format('%.0f', now) .. '|' ..\n"
"            (control and water or meta.water) .. '|R')\n"
"    end\n"
"    return redis.error_reply('ERR global-lb reservation write failed; restore required')\n"
"end\n"
"return result\n";
